### ISSUE TITLE
Adding 'typings' to package.json

### ISSUE THREAD

**Issue by renehamburger** [NejcZdovc/ng2-select2#10]
The TypeScript compiler is unable to locate your type definitions automatically. Would you mind adding `"typings": "dist/ng2-select2.d.ts"` to your package.json? See https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html.

**Comment by NejcZdovc** [comment]
Thank you for the input, will add it right away.

**Comment by NejcZdovc** [comment]
Done.
