### ISSUE TITLE
Demo is out of date

### ISSUE THREAD

**Issue by smaxwellstewart** [NejcZdovc/ng2-select2#12]
Hey trying to see how this is working. Kinda made difficult because the demo and plunkr are out of date.

**Comment by smaxwellstewart** [comment]
Sorry should have said this at the start thank you so much for your hard efforts releasing this!

**Comment by NejcZdovc** [comment]
Hi, will try to update plunker and demo page today.

**Comment by NejcZdovc** [comment]
Updated plunker version to the latest version. Demo for the gh-page will be updated in the coming days.

**Comment by NejcZdovc** [comment]
Added new demo to the gh-pages generated with CLI. You can now see demo on branch `demo`
