### ISSUE TITLE
Build breaking due to jQuery issue

### ISSUE THREAD

**Issue by shivaluthra29** [NejcZdovc/ng2-select2#122]
`ERROR in /node_modules/@types/select2/index.d.ts (113,20): 'JQuery' only refers to a type, but is being used as a namespace here.
`
This is breaking due to import of @types/select2@^4.0.42, which was updated about 17 hours back to version 4.0.45

Resolution: add ` "@types/select2": "4.0.42"` to package.json

@NejcZdovc : can we change the import to the last tested and working version of @types/select2

Thanks in advance

**Comment by darron1217** [comment]
Same here..

**Comment by darron1217** [comment]
@NejcZdovc I created really simple PR to Fix this issue :)
