### ISSUE TITLE
Plunker demo does not work

### ISSUE THREAD

**Issue by b0bi79** [NejcZdovc/ng2-select2#15]
Browser: Chrome
Console output:
run.plnkr.co/:1 XMLHttpRequest cannot load https://npmcdn.com/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://run.plnkr.co' is therefore not allowed access.
zone.js:323 Error: (SystemJS) Error: XHR error loading https://npmcdn.com/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js(…)ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
run.plnkr.co/:1 XMLHttpRequest cannot load https://npmcdn.com/@angular/core/bundles/core.umd.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://run.plnkr.co' is therefore not allowed access.
run.plnkr.co/:1 XMLHttpRequest cannot load https://npmcdn.com/@angular/platform-browser/bundles/platform-browser.umd.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://run.plnkr.co' is therefore not allowed access.
run.plnkr.co/:1 XMLHttpRequest cannot load https://npmcdn.com/ng2-select2@0.4.2//ng2-select2.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://run.plnkr.co' is therefore not allowed access.

**Comment by NejcZdovc** [comment]
Hi, I think that plunker have some issues. Demo was working, but now it's not. I also tried official angular demo and it's not working. You can check it out [here](https://angular.io/resources/live-examples/quickstart/ts/plnkr.html).

**Comment by NejcZdovc** [comment]
Plunker updated to the latest version.
