### ISSUE TITLE
passing dynamic data

### ISSUE THREAD

**Issue by vsanat** [NejcZdovc/ng2-select2#17]
hi Guys,

Is it possible to pass dynamic data to the select?
Because I am trying to get data from rxjs observable and trying to bind it to the [data] but its not taking?
(Its only taking static data in my case)

Is it possible to bind data to the select2 element which is result of http call?

**Comment by NejcZdovc** [comment]
For now it's not possible, but I think can be done quite easily. Let me think about it

**Comment by NejcZdovc** [comment]
I release version 0.6.0 beta where you can test it out. Please let me know if it's working ok for you.

`npm i ng2-select2@0.6.0-beta.0`

**Comment by vsanat** [comment]
Sure I will try. Thank you
