### ISSUE TITLE
Tab in forms

### ISSUE THREAD

**Issue by markcooper** [NejcZdovc/ng2-select2#19]
Pressing tab while focused on this component doesn't continue to the next field currently.

**Comment by NejcZdovc** [comment]
I think this is a problem with select2. I tried on their page and if I click on first example, focus it and then press tab I am returned to the first tab not the next one.

https://select2.github.io/examples.html

**Comment by diegodesouza** [comment]
I'm experiencing the same issue in my forms. Any suggestion?
