### ISSUE TITLE
Modularize it to able to compile it with AoT

### ISSUE THREAD

**Issue by agustincelentano** [NejcZdovc/ng2-select2#20]
Hi, 
Would be possible to put it as a Module? It's in order to be importable from App Module and use AoT compilation at the same time. 

Thanks in advance.

**Comment by NejcZdovc** [comment]
Will add it in version 0.7

**Comment by agustincelentano** [comment]
Is it possible to add it to my project as a module? Not seen in the samples. Actually, it suggest to add it by the metadata "declarations".

**Comment by NejcZdovc** [comment]
Fixed in README.md. Yes you can import module
