### ISSUE TITLE
ng2-select2 not working

### ISSUE THREAD

**Issue by usmanwalana** [NejcZdovc/ng2-select2#21]
I have installed the package and followed the plunker example but it is not working.
I have created an [issue](https://github.com/usmanwalana/select/issues/1) with code. Please have a look.
<img width="1439" alt="screen shot 2016-11-14 at 10 53 01 pm" src="https://cloud.githubusercontent.com/assets/12783879/20299168/7a69f7e6-ab3b-11e6-99ec-7175972998cd.png">

**Comment by NejcZdovc** [comment]
You need to install jquery type and add all types to the tsconfig.json. 

1. `npm i @types/jquery -D`
2. Add types to the tsconfig.json
```
"types": [
  "node",
  "jquery",
  "select2"
]
```

**Comment by NejcZdovc** [comment]
You need to know that plunker is runing on systemjs, but CLI and all angular 2 is now running on a webpack

**Comment by usmanwalana** [comment]
I installed jquery type and added types to tsconfig.json you can see in the latest commit. But still it gives same error. Yes i know that my project is running on webpack but how to make plunker demo work on webpack?

**Comment by NejcZdovc** [comment]
What is the new error?

Difference between systemjs and webpack is how resources are defined add loaded, combined etc. What ever is used doesn't impact this plugin. It will just impact initial configuration.

**Comment by usmanwalana** [comment]
This is how my console looks like now.
<img width="1440" alt="screen shot 2016-11-15 at 3 16 19 pm" src="https://cloud.githubusercontent.com/assets/12783879/20301777/8f52bdb8-ab46-11e6-8dae-6898043d2cd2.png">

**Comment by NejcZdovc** [comment]
I created PR https://github.com/usmanwalana/select/pull/2 and fixed everything, so now it's working.

**Comment by usmanwalana** [comment]
I followed your changes and now the plugin works. But it only works for static data. If i load data from web service it does not show anything. You can see my latest commit to see the code. You will get the idea from attached image.
<img width="866" alt="screen shot 2016-11-15 at 6 29 14 pm" src="https://cloud.githubusercontent.com/assets/12783879/20307652/3238aa90-ab62-11e6-9303-65d6098bc35d.png">

**Comment by NejcZdovc** [comment]
You need to create observable and then add async pipe to the data input in select2.

https://angular.io/docs/ts/latest/guide/pipes.html#!#async-pipe

https://angular.io/docs/ts/latest/guide/server-communication.html

**Comment by usmanwalana** [comment]
I have read these two links. The http part is working fine because i am getting data and convert it to json successfully, but i dont know how to implement asyn pipe in my project. The example given in the docs of async pipe is very simple. I am having trouble in understanding how it would work on select2 in my project. As i am new to angular can you please tell what files i need to modify and what to add? 
I will be very grateful.

**Comment by NejcZdovc** [comment]
The problem is not in select2, you need to create observable that you will pass into data input in select2 tag. You should read some materials about observable and modifiers such as map from rxjs.

**Comment by Tekorius** [comment]
I am also struggling with this issue. I tried creating an observable, but it doesn't seem to load the select.

![image](https://cloud.githubusercontent.com/assets/17677026/20344191/6c20ecd4-abfa-11e6-8fc6-9229bda68b47.png)

![image](https://cloud.githubusercontent.com/assets/17677026/20344212/7e038484-abfa-11e6-8066-5d89674b65fa.png)

And this is the result I get:

![image](https://cloud.githubusercontent.com/assets/17677026/20344224/8fb89390-abfa-11e6-9be6-c6e5743df70e.png)


If I try to just put data in statically then it works fine.

**Comment by NejcZdovc** [comment]
I will take a closer look again, but as far as I was testing this plugin was working correctly. Will let you know soon

**Comment by NejcZdovc** [comment]
Async is working correctly. 

@Tekorius but where you actually send any data to the observable? You just created empty observable.

@usmanwalana As you can see here https://github.com/usmanwalana/select/pull/3 async is working correctly.

**Comment by usmanwalana** [comment]
@NejcZdovc You are an awesome human being. Hats off to your work. It is working now. I will continue exploring this and get back to you if i get stuck.
Thank you so much for helping me.

**Comment by Tekorius** [comment]
@NejcZdovc I see now in the pull request for usmanwalana. The problem is that even though the Observable is instantiated, it still seems to return null value inside. That PR really helped.
