### ISSUE TITLE
NPM Install of ng2-select2 broken

### ISSUE THREAD

**Issue by mwaarna** [NejcZdovc/ng2-select2#28]
npm install ng2-select2  

appears to be broken and peg's CPU to 100% when initializing select2.

I had to grab the version from your plunker demo:
https://unpkg.com/ng2-select2@0.5.1/

to fix the issue.

**Comment by NejcZdovc** [comment]
So you get 100% when you are lunching your application or when you are installing ng2-select?

**Comment by NejcZdovc** [comment]
Ok I managed to reproduce the problem, will try to fix it

**Comment by NejcZdovc** [comment]
Fixed in version 0.6.2
