### ISSUE TITLE
this.element.select2 is not a function

### ISSUE THREAD

**Issue by minhtam-nguyennhat** [NejcZdovc/ng2-select2#30]
Hi,

So I added this import line into app.module.ts

`import { Select2Module } from 'ng2-select2';`

upon running the application I got this error

> this.element.select2 is not a function

Could you please shed some lights on how to resolve this issue?

Thanks,
Tam

**Comment by NejcZdovc** [comment]
You need to add select2 javascript as well

https://github.com/NejcZdovc/ng2-select2/blob/demo/src/index.html#L11

**Comment by NejcZdovc** [comment]
In version 0.6.3 you will not receive error if library is missing, but instructions how to fix it in the console.

**Comment by minhtam-nguyennhat** [comment]
Thanks. I managed to get it working but still not too sure what did really happened.

I'm using webpack at the moment. So what I did was 

- npm install select2 jquery package

- throw this inside app.module.ts
`require('select2');`

And it worked ! (I was like WTF did I just do ~.~)

At the moment, I'm looking into this section here of the webpack.config.js, try to figure out how I can make select2 available across the whole app.

`  plugins: [
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery"
    }),`

**Comment by NejcZdovc** [comment]
What you did with `require('select2');` is include library into the bundle of the webpack. I think that direction that you are exploring now is a lot better.

I would suggest to read trough this options and find one that most suits you.

https://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack#answer-2898947

**Comment by NejcZdovc** [comment]
Readme is now improved so you can check it out there as well.
