### ISSUE TITLE
No provider for Render!

### ISSUE THREAD

**Issue by oscarpr** [NejcZdovc/ng2-select2#34]
![image](https://cloud.githubusercontent.com/assets/8620190/21288030/6a731b82-c446-11e6-922d-085462984ed6.png)

some help?

**Comment by oscarpr** [comment]
using angular 2.0.0

**Comment by NejcZdovc** [comment]
Hi, I am aware of this error, but it happens only in some specific scenarios. Can you please provide some more informations about your code, maybe github link or plnkr. Thank you

**Comment by oscarpr** [comment]
it appear when i go inside a module where i imported the select2module, i was using v0.5.1 and when i upgraded the library  i got the error.

**Comment by NejcZdovc** [comment]
Can you paste your package.json? In version 0.7.0 renderer was added, so it's normal that for version 0.5.1 everything was working correctly.

**Comment by oscarpr** [comment]
`{
  "name": "krgo",
  "version": "0.0.1",
  "description": "Granada krgo app - skin",
  "scripts": {
    "install": "napa",
    "build:dev": "webpack --config config/webpack.dev.js --progress --profile",
    "build:prod": "webpack --config config/webpack.prod.js  --progress --profile --bail",
    "build": "npm run build:dev",
    "ci": "npm run lint && npm test && npm run e2e",
    "clean:dist": "npm run rimraf -- dist",
    "clean:install": "npm set progress=false && npm install",
    "clean:start": "npm start",
    "clean": "npm cache clean && npm run rimraf -- node_modules dist",
    "github-deploy:dev": "webpack --config config/webpack.github-deploy.js --progress --profile --github-dev",
    "github-deploy:prod": "webpack --config config/webpack.github-deploy.js --progress --profile --github-prod",
    "lint": "npm run tslint \"src/**/*.ts\"",
    "postversion": "git push && git push --tags",
    "prebuild:dev": "npm run clean:dist",
    "prebuild:prod": "npm run clean:dist",
    "preclean:install": "npm run clean",
    "preclean:start": "npm run clean",
    "preversion": "npm test",
    "rimraf": "rimraf",
    "server:dev:hmr": "npm run server:dev -- --inline --hot",
    "server:dev": "webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/",
    "server:prod": "http-server dist --cors -p 3001",
    "server": "npm run server:dev",
    "start:hmr": "npm run server:dev:hmr",
    "start": "npm run server:dev",
    "tslint": "tslint",
    "typedoc": "typedoc",
    "version": "npm run build",
    "watch:dev:hmr": "npm run watch:dev -- --hot",
    "watch:dev": "npm run build:dev -- --watch",
    "watch:prod": "npm run build:prod -- --watch",
    "watch:test": "npm run test -- --auto-watch --no-single-run",
    "watch": "npm run watch:dev",
    "webpack-dev-server": "webpack-dev-server",
    "webpack": "webpack"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@angular/router": "3.0.0",
    "@angularclass/conventions-loader": "1.0.2",
    "@angularclass/hmr": "1.2.1",
    "@angularclass/hmr-loader": "3.0.2",
    "@angularclass/request-idle-callback": "1.0.7",
    "@angularclass/webpack-toolkit": "1.3.3",
    "angular2-autosize": "1.0.0",
    "angular2-google-maps": "0.15.0",
    "angular2-text-mask": "0.22.0",
    "animate.css": "3.5.1",
    "assets-webpack-plugin": "3.4.0",
    "awesome-bootstrap-checkbox": "1.0.0-alpha.4",
    "bootstrap": "4.0.0-alpha.4",
    "bootstrap-colorpicker": "2.3.6",
    "bootstrap-datepicker": "1.6.4",
    "bootstrap-markdown": "2.10.0",
    "bootstrap-select": "1.11.2",
    "bootstrap-slider": "9.2.0",
    "core-js": "2.4.1",
    "d3": "3.5.17",
    "dropzone": "4.3.0",
    "easy-pie-chart": "2.1.7",
    "font-awesome": "^4.7.0",
    "fullcalendar": "3.0.1",
    "glyphicons-halflings": "1.9.0",
    "hammerjs": "2.0.8",
    "http-server": "0.9.0",
    "ie-shim": "0.1.0",
    "jasny-bootstrap": "3.1.3",
    "jquery": "3.1.0",
    "jquery-flot": "0.8.3",
    "jquery-slimscroll": "1.3.8",
    "jquery-sparkline": "2.3.2",
    "jquery-ui": "git://github.com/jquery/jquery-ui.git#1.11.4",
    "jquery.animate-number": "0.0.13",
    "jvectormap": "2.0.4",
    "magnific-popup": "1.1.0",
    "markdown": "0.5.0",
    "messenger": "git+https://github.com/HubSpot/messenger.git#v1.4.2",
    "moment": "2.15.1",
    "morris.js": "0.5.0",
    "ng2-bootstrap": "1.1.5",
    "ng2-datetime": "^1.2.0",
    "ng2-file-upload": "^1.1.2",
    "ng2-modal": "0.0.21",
    "ng2-select": "^1.1.1",
    "ng2-select2": "1.0.0-beta.2",
    "ng2-table": "1.1.0",
    "node-forge": "^0.6.42",
    "nvd3": "1.8.4",
    "pace": "git://github.com/HubSpot/pace.git#v0.7.7",
    "parsleyjs": "2.4.4",
    "rickshaw": "1.6.0-rc.0",
    "rxjs": "5.0.0-beta.12",
    "select2": "4.0.3",
    "select2-bootstrap-theme": "0.1.0-beta.9",
    "shufflejs": "4.0.2",
    "webpack-raphael": "2.1.4",
    "widgster": "0.0.3",
    "zone.js": "0.6.25"
  },
  "napa": {
    "jquery-ui2": "git://github.com/jquery/jquery-ui.git#1.12.0-rc.2",
    "bootstrap-application-wizard": "git://github.com/amoffat/bootstrap-application-wizard.git#3768da3142f43428c5f63284407a2481a9e283d3",
    "twitter-bootstrap-wizard": "git://github.com/VinceG/twitter-bootstrap-wizard.git#62a9aca8cc61fdb496c4bf7b92e1ff70c698667e",
    "jvectormap-world": "http://jvectormap.com/js/jquery-jvectormap-world-mill-en.js",
    "bootstrap_calendar": "https://github.com/xero/bootstrap_calendar.git#1.0.1",
    "jquery.nestable": "https://github.com/dbushell/Nestable.git#4f93032cfafe2002f24ed6bd7dc1510931498503",
    "jquery.flot.animator": "https://github.com/Codicode/flotanimator.git#3c256c0183d713fd3bf41d04417873928eb1a751",
    "flot-orderBars": "https://github.com/emmerich/flot-orderBars.git#98081459571f60f7d95cc79a848c4f558d077486",
    "jQuery-Mapael": "https://github.com/neveldo/jQuery-Mapael.git#0.7.1",
    "skycons": "https://github.com/darkskyapp/skycons.git#7095ecf5f653dbcadbddb0d317b42e65fe091eae"
  },
  "devDependencies": {
    "@types/core-js": "0.9.34",
    "@types/hammerjs": "2.0.33",
    "@types/jasmine": "2.2.34",
    "@types/node": "6.0.38",
    "@types/source-map": "0.1.27",
    "@types/uglify-js": "2.0.27",
    "@types/webpack": "1.12.34",
    "angular2-template-loader": "0.5.0",
    "awesome-typescript-loader": "2.2.1",
    "codelyzer": "0.0.28",
    "copy-webpack-plugin": "3.0.1",
    "css-loader": "0.25.0",
    "exports-loader": "0.6.3",
    "expose-loader": "0.7.1",
    "file-loader": "0.9.0",
    "html-webpack-plugin": "2.21.0",
    "imports-loader": "0.6.5",
    "istanbul-instrumenter-loader": "0.2.0",
    "json-loader": "0.5.4",
    "metrojs": "0.9.77",
    "napa": "2.3.0",
    "node-sass": "3.9.3",
    "parse5": "1.3.2",
    "raw-loader": "0.5.1",
    "rimraf": "2.5.2",
    "sass-loader": "4.0.2",
    "source-map-loader": "0.1.5",
    "string-replace-loader": "1.0.5",
    "style-loader": "0.13.1",
    "to-string-loader": "1.1.4",
    "ts-helpers": "1.1.1",
    "ts-node": "1.3.0",
    "tslint": "3.15.1",
    "tslint-loader": "2.1.3",
    "typedoc": "0.4.5",
    "typescript": "2.0.0",
    "url-loader": "0.5.7",
    "webpack": "2.1.0-beta.22",
    "webpack-dev-middleware": "1.6.1",
    "webpack-dev-server": "2.1.0-beta.2",
    "webpack-md5-hash": "0.0.5",
    "webpack-merge": "0.14.1"
  },
  "overrides": {
    "rickshaw": {
      "dependencies": {
        "d3": "3.5.5"
      }
    }
  },
  "engines": {
    "node": ">= 4.2.1",
    "npm": ">= 3"
  }
}`

this is my package.json what do i have to add?

**Comment by NejcZdovc** [comment]
I don't think that you need to add anything. I just wanted to see your `package.json` to find a pattern why some users are receiving this error and some not. Sadly I didn't notice any pattern so I will investigate further.

**Comment by oscarpr** [comment]
Ok man. I would appreciate. I really need it

**Comment by NejcZdovc** [comment]
Sure not a problem, hope that I will find a solution as soon as possible.

**Comment by NejcZdovc** [comment]
I found a quick solution. For now instead of including `Select2Module` into `imports`, add `Select2Component` into `declaration`. I will fix so that module will work as well.

**Comment by oscarpr** [comment]
Ok i will try, but the problem is that i need use the select2 in all the app and i cant include it in several declaratios.

**Comment by NejcZdovc** [comment]
You can include it into your top level NgModule and will work for all child components.

**Comment by oscarpr** [comment]
thanks i did it, hope for news. god bless u

**Comment by oscarpr** [comment]
i did it but, it say 'data' is not a known property of 'select2'

**Comment by NejcZdovc** [comment]
I just released beta3, try with this version. You can try first with `Select2Module` in `imports`

**Comment by oscarpr** [comment]
OK!!! it works. but i have this problem now, this is because i change the value of 'value' input. do u know what i mean?

![image](https://cloud.githubusercontent.com/assets/8620190/21289948/10297dba-c478-11e6-99fc-cd751c5c8571.png)

**Comment by NejcZdovc** [comment]
Hard to help you here without knowing a code. Some informations about this error:

https://github.com/angular/angular/issues/6005
https://stackoverflow.com/questions/34364880/expression-has-changed-after-it-was-checked/34364881#34364881
https://github.com/angular/angular/issues/10131

**Comment by oscarpr** [comment]
OK!! really really thanks. 
Dios te lo pague, regards!!!!

**Comment by NejcZdovc** [comment]
Happy to help
