### ISSUE TITLE
valueChanged on multi-select

### ISSUE THREAD

**Issue by GaillardQ** [NejcZdovc/ng2-select2#35]
Hi,
I have a problem with the multi-select....

The method valueChanged used to retrieve the selected data, always returns the first selected element....

For example : 
values = [val1, val2, val3, val4]

I select val4, it displays val4, then I select val2, it displays val2, but then I select val3, but still displays val2.... When you select item, they are sorted by text and valueChanged return the id of the first element...

And when you clear one selected element, the event is not emitted...

Is there a solution ?

**Comment by NejcZdovc** [comment]
I just published version 1.0.0-beta.4. Can you please try it out?

**Comment by GaillardQ** [comment]
Great !

I got an array of the selected values !

Thanks !
