### ISSUE TITLE
Field disabled

### ISSUE THREAD

**Issue by GaillardQ** [NejcZdovc/ng2-select2#36]
Hi,
I have another suggestion to improve your great component !

Unless I'm mistaken, there is no way to disable the field : option [disabled]="isDisabled" does not work => Can't bind to 'disabled' since it isn't a known property of 'select2'. 

Good luck :D
Quentin

**Comment by NejcZdovc** [comment]
Sure will take a look and implement it tomorrow, today sadly I don't have any spare time.
