### ISSUE TITLE
Placeholder in options input doesnt work

### ISSUE THREAD

**Issue by oscarpr** [NejcZdovc/ng2-select2#37]

**Comment by NejcZdovc** [comment]
It's working, but you need to specify empty element in your data or assign placeholder to your none selector.

First scenario:
```
this.exampleData = [
       {
        id: '',
        text: 'Empty'
      },
      {
        id: 'opt1',
        text: 'Options 1'
      },
      {
        id: 'opt2',
        text: 'Options 2'
      },
      {
        id: 'opt3',
        text: 'Options 3'
      },
    ];

this.option = {
    placeholder: 'Select an option'
}
```

Second option:
```
this.exampleData = [
       {
        id: '0',
        text: 'Select'
      },
      {
        id: 'opt1',
        text: 'Options 1'
      },
      {
        id: 'opt2',
        text: 'Options 2'
      },
      {
        id: 'opt3',
        text: 'Options 3'
      },
    ];

this.option = {
   placeholder: {
         id: '0', // the value of the option
         text: 'Select an option'
    }
}
```

**Comment by oscarpr** [comment]
Ok!! thanks

**Comment by VigneswaranMuruganandan** [comment]
both scenario , i have tried. its not working

**Comment by graigjanssen** [comment]
I am not able to get this to work.

I have tried both suggested solutions by adding an empty option as first element in my data array:

```
myData = [
  {
    id: '',
    text: 'Empty'
  },
  ...more entries
]
```
Before adding placeholder to options object, I see the 'Empty' option in the select menu.  After adding `placeholder: 'My placeholder text'` to options object, the 'Empty' option is no longer displayed in the select menu, but the placeholder is not displayed.  When I inspect the element, the 'Empty' option is still there, just isn't displayed now.  I get the same result when trying the second solution - giving my empty option an id of `'0'` and making the placeholder an object with that id and text property.  

Thanks for any help in clearing this up.
