### ISSUE TITLE
npm install reports invalid

### ISSUE THREAD

**Issue by mochoamat** [NejcZdovc/ng2-select2#39]
hi,

We are installing ng2-select2@0.7.0 because  it's a dependency of Sing@3.3.0 template

we are using @angular/core@2.2.0

The "npm install" and "npm ls" commands prints "ng2-select2@0.7.0 invalid"

if the ng2-select2 package meets angular dependency, why it's being reported as "invalid"?

Thank you

**Comment by NejcZdovc** [comment]
Can you please paste the whole error log and your package.json if possible.
