### ISSUE TITLE
Set dynamically a value after data change

### ISSUE THREAD

**Issue by GaillardQ** [NejcZdovc/ng2-select2#42]
Hi !
I'm currently meeting a problem with your solution...

I can only select a value dynamically once. When I change the data list, I cannot....

Could you take a look for that problem please ?
Your solution is really great, but this is missing.

Quentin

**Comment by GaillardQ** [comment]
Don't mind this, I found a solution....

**Comment by Dhamu143** [comment]
how can I set this startValue manually ?
