### ISSUE TITLE
select2.component Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by et-taousy** [NejcZdovc/ng2-select2#45]
i try to use this api bur i get some error : 
Uncaught ReferenceError: require is not defined
    at ng2-select2.ts:1
http://localhost:3000/node_modules/ng2-select2/src/select2.component Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:25 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/ng2-select2/src/select2.component
	Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/ng2-select2/src/select2.component
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:851:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]

but when i add : 'ng2-select2': 'npm:ng2-select2/ng2-select2.js', to sytem.config.js i get ng2-select.component not found.

**Comment by NejcZdovc** [comment]
I just released new version beta.7, can you try it out and see if this version fixed your problem. Thank you
