### ISSUE TITLE
using [value] with multiple select

### ISSUE THREAD

**Issue by mtsvr** [NejcZdovc/ng2-select2#47]
I need to display initial values as selected on a multiple select input.
In order to achieve this I've tried passing an array to [value]. When the initial values array has only one value (always of type string), the option is displayed as selected. However, when the initial values array has 2 or more values, nothing is displayed as selected.

Is there a way I can work around this issue?

**Comment by NejcZdovc** [comment]
#46 is addressing this issue. Will review it today

**Comment by mtsvr** [comment]
Thanks! I'll be subscribing to that issue then. Thank you for the quick reply.

**Comment by htrex** [comment]
My latest pull request (#48) works both with string and array input for the value.
If passing a string, it can be a single id, or a comma separated list of ids, eg: "1,2,3,4"

**Comment by NejcZdovc** [comment]
Closed with ccbc858

**Comment by ltorresortiz** [comment]
Hi!! I have a question with this. I can not do work with initial values as selected in a multiple selection input.

Even if you have done the commit: ccbc858. 

My code looks like: 

<select2 [value]="specialtiesSelected" [data]="specialtiesData" (valueChanged)="changeSpecialty($event)" [options]="options">
</select2>

where specialtiesSelected is equals to: public specialtiesSelected: string = "2,3"; (2,3 are id in my data)

Do you can help me please?? :( With any examples for this?

Regards,

Eleana

**Comment by htrex** [comment]
I think the problem is with the commit https://github.com/NejcZdovc/ng2-select2/commit/4396df6634a08594bfeb962f3b105e11cfec394b 

I needed to add the following code at the beginning of setElementValue function.
`
if(typeof newValue === 'string') {
     newValue = newValue.split(',');
}
`

**Comment by ltorresortiz** [comment]
No, I am using the commit code: 4396df6 and it is not works. 
Do yo have idea what it's happen?

**Comment by htrex** [comment]
I may try to set the value with this workaround.

[value]="yourCommaSeparetedString ? yourCommaSeparetedString.split(',') : '' "

**Comment by ltorresortiz** [comment]
Thanks a lot, it's works :)

Regards

**Comment by dpk-kakkar** [comment]
Hi Guys, I am using multiselect dropdown with ajax call, and I want to show previously selected value, can say default value. Solution defined above is not working for me.I am not able to pass value to select2. Can somebody please help?

**Comment by htrex** [comment]
for a single select you don't need  `yourCommaSeparetedString ? yourCommaSeparetedString.split(',') : ''`
if your model contains a single value just pass that

**Comment by yogesh61990** [comment]
its work for me and show selected item, but cross button not working on it , if anybody how to we solve it please help.
