### ISSUE TITLE
Please tell how can i prepopulate multi selected values

### ISSUE THREAD

**Issue by venkatesh-mothe** [NejcZdovc/ng2-select2#51]
Please tell how can i prepopulate multi selected values.

using ng2-select2, i can populate only one selected value. Could you please tell me code or example for multiple selected values binding.

![image](https://cloud.githubusercontent.com/assets/19218592/22495931/87b74012-e86b-11e6-838d-55f8c698ad34.png)

Thanks

**Comment by htrex** [comment]
Check if you are using the latest version as there are fixes regarding multiselect.
Then you can pass a comma separated string of ids or an array of ids.
Please note that the output from the component will be a comma separated string of ids.

**Comment by NejcZdovc** [comment]
I think that I will change this, because it's not really friendly for a developers. Service will almost never return comma separated string for example, you always work with arrays.

**Comment by venkatesh-mothe** [comment]
Thanks htrex and NejcZdovc...

I used the below array to bind the data.

this.exampleData = [
            {
                id: '1',
                text: 'Basic 1'
            },
            {
                id: '2',
                text: 'Basic 2'
            },
            {
                id: '3',
                text: 'Basic 3'
            },
            {
                id: '4',
                text: 'Basic 4'
            }
        ];
i can successfully bind the data.
![image](https://cloud.githubusercontent.com/assets/19218592/22636919/c0c89c50-ec64-11e6-93e6-85c438c0e9ba.png)

then, i selected 'Basic 1' & 'Basic 2' and saved those options in database.
![image](https://cloud.githubusercontent.com/assets/19218592/22636949/f1cb7a66-ec64-11e6-8370-07caeb49c4b7.png)

Here the problem is, i unable to prepopulate the 'Basic 1' and 'Basic 2' options next time when we opens the form.

i tried with comma separated values and arrays. but no use.
<select2 [data]="exampleData" [options]="options" id="sid1" class="sid1" [value]="testdata"></select2>

here, testdata is an array with selected ids.

i am using latest version of ng2-select2 (i.e 1.0.0-beta.7)

Please let us know your suggestions.

Thanks in advance.

**Comment by NejcZdovc** [comment]
I just published new version `1.0.0-beta.8`, there is also a new demo for multiple values.

**Comment by venkatesh-mothe** [comment]
Thanks NejcZdovc. Its working now :)
