### ISSUE TITLE
this.element.select2 is not a function

### ISSUE THREAD

**Issue by jeusdi** [NejcZdovc/ng2-select2#52]
I'm getting this message from angular2:

> EXCEPTION: Uncaught (in promise): Error: Error in ./Signin class Signin - inline template:59:20 caused by: <b>this.element.select2 is not a function</b>
["./node_modules/ng2-select2/src/select2.component.js"]/</Select2Component</Select2Component.prototype.ngAfterViewInit@http://localhost:3002/1.chunk.js:20408:13
anonymous/View_Signin0.prototype.detectChangesInternal@/SigninModule/Signin/component.ngfactory.js:771:40
ac_vendor<["./node_modules/@angular/core/src/linker/view.js"]/AppView</AppView.prototype.detectChanges@http://localhost:3002/vendor.bundle.js:49160:9
ac_vendor<["./node_modules/@angular/core/src/linker/view.js"]/DebugAppView</DebugAppView.prototype.detectChanges@http://localhost:3002/vendor.bundle.js:49355:13
anonymous/View_Signin_Host0.prototype.detectChangesInternal@/SigninModule/Signin/host.ngfactory.js:36:3
ac_vendor<["./node_modules/@angular/core/src/linker/view.js"]/AppView</AppView.prototype.detectChanges@http://localhost:3002/vendor.bundle.js:49160:9
ac_vendor<["./node_mod[…]

I've added dependencies on my compoenent and module:

Module:
```
import { AlertModule } from 'ng2-bootstrap/ng2-bootstrap';
import { Select2Module } from 'ng2-select2';

@NgModule({
  declarations: [
    Signin
  ],
  imports: [
    CommonModule,
    ReactiveFormsModule,
    AlertModule,
    Select2Module,
    RouterModule.forChild(routes),
  ]
})
export default class SigninModule {
  static routes = routes;
}
```

Component:
```
import { Select2OptionData } from 'ng2-select2';
declare var jQuery: any;
@Component(...)
export class Signin implements OnInit {

    private plans: Array<Select2OptionData>;

    constructor()
    {
        this.alerts = [];
        this.plans = [];
    }
ngOnInit():void {
        this.form = this.fb.group({
            mail: ['', Validators.required],
            passwd: ['', Validators.minLength(6)],
            passwdConfirm: ['', Validators.minLength(6)],
            cname: ['', Validators.required],
            sname: ['']
        });

        var p = jQuery('.parsleyjs').parsley();

        this.plans = [{
            id: 'Magellanic',
            text: 'Large Magellanic Cloud'
            },
            {
                id: 'Andromeda',
                text: 'Andromeda Galaxy'
            },
            {
                id: 'Sextans',
                text: 'Sextans A'
            }];
    }

    select2Changed(e: any): void {
        this.selected = e.value;
    }

    getSelect2DefaultList(): Array<Select2OptionData> {
        return this.plans;
    }
```

My template is using `select2` directive as:
```
    <select2 id="default-select"
        (valueChanged)="select2Changed($event)"
        [data]="getSelect2DefaultList()" [width]="250" [theme]="'bootstrap'"></select2>
```

Any ideas?

**Comment by NejcZdovc** [comment]
Did you added select2.js to your bundle?

**Comment by jeusdi** [comment]
Solved! Thanks
