### ISSUE TITLE
Populate select2 using Rxjs

### ISSUE THREAD

**Issue by jeusdi** [NejcZdovc/ng2-select2#53]
I've binded `select2` directive to a component field `plans`:

    <select2 id="default-select"
        (valueChanged)="select2Changed($event)"
        [data]="plans"   <<<<<<<<<<<<<<<<
        [width]="250"
        [theme]="'bootstrap'">
    </select2>

I'm populating `plans` field using Rxjs:
```
export class Signin implements OnInit {
    private plans: Array<Select2OptionData>;
    constructor() {
        this.plans = [];
    }
    ngOnInit():void {
        this.serverService
            .list()
            .subscribe(
                (result: any) => {
                    this.plans.splice(0, this.plans.length);
                    for (let plan of result)
                        this.plans.push({id: plan.id, text: plan.name});
                },
                (error: any) => {

                }
            );
    }
}
```
Nevertheless, `select2` is not populated. I've debugged data is well received and pushed on on `plans` field.

Should I take in mind any issue?

**Comment by NejcZdovc** [comment]
Can you please debug it a little bit more. Is this (function)[https://github.com/NejcZdovc/ng2-select2/blob/master/lib/ng2-select2.component.ts#L58] called when you receive all success from subscribe?

**Comment by jeusdi** [comment]
I've set a breakpoint on:

```
Select2Component.prototype.ngOnChanges = function (changes) {
        if (!this.element) {  <<<<<<<<<<<<<<<<<<BREAKPOINT
            return;
        }
```

Nevertheless, when the breakpoint is active, the `select2` is populated. When the breakpoint is disabled, the `select2` is not populated.

When I go on on the code execution it goes in to `return` line.

**Comment by lothern** [comment]
@jeusdi I'm using observables in my solution as well.  I would recommend structuring your code like this:
```
<select2 id="default-select"
    (valueChanged)="select2Changed($event)"
    [data]="plans$ | async"
    [width]="250"
    [theme]="'bootstrap'">
</select2>
```


```
export class Signin implements OnInit {
    private plans$: Subject<any> = new BehaviorSubject([]);
    constructor() {
    }
    ngOnInit():void {
        this.serverService
            .list()
            .subscribe(
                (result: any) => {
                    this.plans$.next(result.map((plan) => {
                      return {id: plan.id, text: plan.name};
                    }));
                },
                (error: any) => {

                }
            );
    }
}
```

This takes advantage of the built-in subscription to an observable by Angular in the template.  And we can stay immutable by transforming the results from your service with map, then nexting (new word) that new array into the stream for our template subscription to see.

I've used this technique in all of my select2 bindings and it works like a charm.

FYI, Subject and BehaviorSubject are imported from rxjs.

**Comment by efriandika** [comment]
How to set default value, if we are populating data from an Observable ?
