### ISSUE TITLE
Please add Select2 library (js file) to the project

### ISSUE THREAD

**Issue by xtoff** [NejcZdovc/ng2-select2#54]
Hello,

I'm getting the following message in console when loading your select component:
"Please add Select2 library (js file) to the project. You can download it from https://github.com/select2/select2/tree/master/dist/js."

I did everything for the installation.. 

1. Installed Jquery & Select2 and added it to my angular-cli.json:
`"scripts": [
"../node_modules/jquery/dist/jquery.js",
        "../node_modules/select2/dist/js/select2.full.js"
]`

2. Installed ng2-select2 via npm 
3. Added ng2-select2 to my NgModule imports of my template where I added my select2 component.

module:
`import {Select2Module} from "ng2-select2";`

`@NgModule({
  declarations: [
    RegisterCompanyComponent
  ],
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    Select2Module,
    RouterModule.forChild(routes),
  ]
})`

html:
`<select2 [data]="countries" [width]="150"></select2>`

If I look at the scripts.bundle.js in my browsers source, the select2 library is in there:
`module.exports = "/*!\r\n * Select2 4.0.3\r\n * https://select2.github.io\r\n`

Here are the versions I use:

- ng2-select2: 1.0.0-beta.7
- select2: 4.0.3
- angular-cli: 1.0.0-beta.28.3
- node: 7.5.0
- os: darwin x64
- @angular/common: 2.4.5
- @angular/compiler: 2.4.5
- @angular/core: 2.4.5
- @angular/forms: 2.4.5
- @angular/http: 2.4.5
- @angular/platform-browser: 2.4.5
- @angular/platform-browser-dynamic: 2.4.5
- @angular/router: 3.4.5
- @angular/compiler-cli: 2.4.5

I hope you can help me..

**Comment by ionutiliescu** [comment]
Having the same issue here.

**Comment by NejcZdovc** [comment]
@xtoff I see that you have basic installation via CLI. Is it possible that you would create github repo of your project, so that I can check it out myself?

**Comment by xtoff** [comment]
@NejcZdovc I think that I'm not allowed to do that.. I just created a new angular2 cli project with only jquery, select2 and ng2-select2 and it works.. I think there are some conflicts with other dependencies. I will investigate some more.. :)

**Comment by NejcZdovc** [comment]
@xtoff what if you clone this repo https://github.com/NejcZdovc/ng2-select2-demo and try to install it. Is it working?

**Comment by xtoff** [comment]
The demo works perfectly local

**Comment by xtoff** [comment]
@NejcZdovc Problem is fixed! I also imported the library "ng2-select" (https://github.com/valor-software/ng2-select) on the same page, because I wanted to compare :), but when I removed that one, yours worked suddenly, so there is probably a conflict in naming...

I'm glad it works, because your library is a lot better than ng2-select ;-)

**Comment by NejcZdovc** [comment]
Great to hear that :smiley:

**Comment by asongkai** [comment]
Hi There,

I have the same issue, my problem if I navigate from page to page the select is working fine but if I try to reload the page by pressing F5 or click the reload button of the browser then it is not working and see in the console log get the same message.

**Comment by Samshal** [comment]
Hello, 
I also encountered this error after installing another npm package into my project. It was working before the installation.

**The trick** was to move select2 js file to the end of the scripts array in angular.json. I suspect the installed library caused a conflict and making it the last script that gets loaded resolves this conflict.
