### ISSUE TITLE
Please tell how can i set disabled in group when selected values

### ISSUE THREAD

**Issue by madara134** [NejcZdovc/ng2-select2#56]
Please tell how can i set disabled in group when selected values
![image](https://cloud.githubusercontent.com/assets/11155951/22625184/d9a08ccc-ebc1-11e6-8473-b411b7332bea.png)
thanks

**Comment by NejcZdovc** [comment]
Added support for disabled data in version `1.0.0-beta.9`, you can see it used [here](https://github.com/NejcZdovc/ng2-select2-demo/tree/master/src/app/demos/basic)

**Comment by madara134** [comment]
Thanks ! but my error when i update beta 1.0.0-beta.9
![image](https://cloud.githubusercontent.com/assets/11155951/22681698/398dc52a-ed41-11e6-9315-35a5e72852b0.png)
![image](https://cloud.githubusercontent.com/assets/11155951/22681726/5960fd4a-ed41-11e6-905c-2d6298a2cd7e.png)
![image](https://cloud.githubusercontent.com/assets/11155951/22681743/704f9e6c-ed41-11e6-9874-2859398e538e.png)

**Comment by NejcZdovc** [comment]
O shit, sorry. I published new version `1.0.0-beta.10`, this should be resolved.
