### ISSUE TITLE
how to change the styles?

### ISSUE THREAD

**Issue by jaronwright** [NejcZdovc/ng2-select2#69]
Can someone please tell me how I can change the style?

**Comment by NejcZdovc** [comment]
You can pass option `cssImport` with value `false` and then you can add your own style. In new version you will have this option set to `false` by default.

**Comment by jaronwright** [comment]
Thanks man! You should add this to the read me.

**Comment by jaronwright** [comment]
[ts]
Type '{ multiple: true; theme: string; containerCssClass: string; dropdownCssClass: string; cssImport: ...' is not assignable to type 'Select2Options'.
  Object literal may only specify known properties, and 'cssImport' does not exist in type 'Select2Options'.


Hey @NejcZdovc I am seeing this now

**Comment by NejcZdovc** [comment]
It's already in readme, under section [options](https://github.com/NejcZdovc/ng2-select2#options)

**Comment by NejcZdovc** [comment]
@jaronwright which version are you using?

**Comment by jaronwright** [comment]
@NejcZdovc Thanks!
