### ISSUE TITLE
Does this work for multiple?

### ISSUE THREAD

**Issue by rkralston** [NejcZdovc/ng2-select2#7]

**Comment by NejcZdovc** [comment]
I have a plan to redo options, because now they are not really good, but I can add multiple without a lot of problems as a temporary solution. Do you have some time limits about it?

**Comment by rkralston** [comment]
I was supposed to release my product today. i have figured out how to add Angular classes and how to manipulate the data. All I need is to close the selection window onBlur. I cannot hook that event no matter what I do.

Set data:
  @ViewChild('career_level') career_level: SelectComponent
   this.career_level.active = this.getOptions(profile.career_level);

Set CSS:
    _element = jQuery(this.career_level.element.nativeElement).find('.dropdown');
    this.initMultiSelect(_element, profile.career_level.length > 0);

  private initMultiSelect(element: JQuery, valid: boolean) {
    element.addClass("form-control");
    element.attr("required", "true");
    if (valid) {
      this.setCssValid(element);      
    } else {
      this.setCssInvalid(element);
    }
  }

  private setCssValid(element: JQuery) {
    element.addClass('ng-valid');
    element.addClass('ng-touched');
    element.removeClass('ng-invalid');
    element.removeClass('ng-pristine');
  }

  private setCssInvalid(element: JQuery) {
    element.removeClass('ng-valid');
    element.addClass('ng-invalid');
  }


If I knew how to run the component's build, I would make theses changes to Component in a branch.

**Comment by rkralston** [comment]
I've also worked around the onBlur.

If you'll post the build process, I'll incorporate these into a branch.

**Comment by rkralston** [comment]
Building now.

**Comment by NejcZdovc** [comment]
Hi, sorry for the delay. I will update cli to the latest version, so that it will use webpack. Because of that build process will be very simple and straight forward.

**Comment by NejcZdovc** [comment]
Added in version 1.0.0
