### ISSUE TITLE
view error when use in angular2-modal

### ISSUE THREAD

**Issue by hong-duc** [NejcZdovc/ng2-select2#73]
I want to use select2 in modal, but the drop down options when click  should show beneath the select2 box inside the modal, but show outside the modal

**Before I click on the select2 box**
![screenshot_20170321_002130](https://cloud.githubusercontent.com/assets/12032550/24112851/67137ce0-0dcd-11e7-9da5-eb7b40ee6438.png)

**After I click on the select2 box**
![screenshot_20170321_002143](https://cloud.githubusercontent.com/assets/12032550/24112895/8dd06dd4-0dcd-11e7-8166-9a090c24f426.png)

**Comment by NejcZdovc** [comment]
@hong-duc check z-index of your modal window and select2 dropdown. I am guessing that you need to increase z-index of dropdown and you should be fine

**Comment by hong-duc** [comment]
@NejcZdovc it work thank you :smile: 
Now the only thing is to figure out how to change it from code
