### ISSUE TITLE
Excuse me, After I set language: 'zh-CN' in select2Options, but found it doesn' work, Is there anthing wrong with me?

### ISSUE THREAD

**Issue by xiehongyang** [NejcZdovc/ng2-select2#84]

**Comment by diandsonc** [comment]
try this:
Include
"../node_modules/select2/dist/js/select2.full.min.js",
 "../node_modules/select2/dist/js/i18n/zh-CN.js",

private select2Options: Select2Options = { language: 'zh-CN' };

<select2 formControlName="Account" [data]="Account| async" [options]="select2Options" width="100%"></select2>

**Comment by xiehongyang** [comment]
@diandsonc Thank u so much
