### ISSUE TITLE
Feature: @Input for placeholder?

### ISSUE THREAD

**Issue by diegodesouza** [NejcZdovc/ng2-select2#95]
Hey guys, thanks for the great work.

I came into an issue in my project where I use multiple select options, and the `options` object doesn't seem be sharable across very well within the same component. At least I didn't find good way of doing so. What would be a good solution for this?

For example, in my form I have options for `suffix`, `title`, `marital status` and so forth?

If we included an @Input for it we'd be able to solve it no? thoughts?

**Comment by hitas** [comment]
What if you, instead of sharing the same object, create new `options` object for each `<select2..>`? And, let's say, pass placeholder into the method?

Something like:

HTML:
`<select2 [options]="getOptions('my precious')" ...></select2>`
TS:
```
    getOptions(placeholderText: string): Select2Options {
        return {
            ...
            placeholder: placeholderText,
            ...
        };
    }
```

**Comment by diegodesouza** [comment]
for now i created a `Pipe`, but the above would also work. Still hoping for the `@Input` though. I'd be cleaner
